var searchData=
[
  ['dacc_0',['DACC',['../sam4sd32c_8h.html#abe68540af3fd10d3b14fb4b9902cb90e',1,'sam4sd32c.h']]],
  ['dacc_5fhandler_1',['DACC_Handler',['../sam4sd32c_8h.html#a4e5ace3081c1889b911e460ec4a1dbd2',1,'sam4sd32c.h']]],
  ['dacc_5firqn_2',['DACC_IRQn',['../sam4sd32c_8h.html#a666eb0caeb12ec0e281415592ae89083afcd76b45935f324df4cacc5bd52b3b6e',1,'sam4sd32c.h']]],
  ['data_3',['Advanced use case - Send a packet of serial data',['../serial_use_case_1.html',1,'serial_quickstart']]],
  ['debugmon_5fhandler_4',['DebugMon_Handler',['../sam4sd32c_8h.html#adbdfb05858cc36fc520974df37ec3cb0',1,'sam4sd32c.h']]],
  ['debugmonitor_5firqn_5',['DebugMonitor_IRQn',['../sam4sd32c_8h.html#a666eb0caeb12ec0e281415592ae89083a8e033fcef7aed98a31c60a7de206722c',1,'sam4sd32c.h']]],
  ['definitions_6',['Definitions',['../group___s_a_m4_s_d32_c__cmsis.html',1,'CMSIS Definitions'],['../group___s_a_m4_s_d32_c__base.html',1,'Peripheral Base Address Definitions'],['../group___s_a_m4_s_d32_c__id.html',1,'Peripheral Ids Definitions'],['../group___s_a_m4_s_d32_c__pio.html',1,'Peripheral Pio Definitions'],['../group___s_a_m4_s_d32_c__reg.html',1,'Registers Access Definitions']]],
  ['definitions_7',['definitions',['../group__interrupt__deprecated__group.html',1,'Deprecated interrupt definitions'],['../group___s_a_m4_s_d32_c__definitions.html',1,'SAM4SD32C definitions']]],
  ['delay_20routines_8',['Delay Routines',['../group__group__common__services__delay.html',1,'Busy-Wait Delay Routines'],['../index.html#mainpage_delay',1,'Delay Routines']]],
  ['delay_2eh_9',['delay.h',['../delay_8h.html',1,'']]],
  ['delay_5fcycles_10',['delay_cycles',['../cycle__counter_8h.html#a84ecb39fb8b32180b27236ae02392d39',1,'cycle_counter.h']]],
  ['delay_5finit_11',['delay_init',['../group__group__common__services__delay.html#ga62d461b94db6352d8ed8442d62ea39fb',1,'delay.h']]],
  ['delay_5fms_12',['delay_ms',['../group__group__common__services__delay.html#gad917a5d772ddbd99ad97a1c999ce40d4',1,'delay.h']]],
  ['delay_5fs_13',['delay_s',['../group__group__common__services__delay.html#gafdccadc6c16847907b3252cdef83e8b0',1,'delay.h']]],
  ['delay_5fus_14',['delay_us',['../group__group__common__services__delay.html#gaf9a0c0e0f880d818a4c2c3ea9fe8cba1',1,'delay.h']]],
  ['dependencies_15',['Dependencies',['../group__ioport__group.html#dependencies',1,'Dependencies'],['../asfdoc_sam_drivers_tc_extra.html#asfdoc_sam_drivers_tc_extra_dependencies',1,'Dependencies'],['../group__gpio__group.html#io_group_platform',1,'Platform Dependencies'],['../group__serial__group.html#serial_group_platform',1,'Platform Dependencies'],['../group__twi__group.html#twi_group_platform',1,'Platform Dependencies'],['../group__twi__group.html#twi_group_platform_slave',1,'Platform Dependencies']]],
  ['deprecated_20interrupt_20definitions_16',['Deprecated interrupt definitions',['../group__interrupt__deprecated__group.html',1,'']]],
  ['deprecated_20list_17',['Deprecated List',['../deprecated.html',1,'']]],
  ['description_18',['Description',['../asfdoc_sam_drivers_tc_example.html#asfdoc_sam_drivers_tc_example_description',1,'']]],
  ['detection_19',['Advanced use case - Interrupt driven edge detection',['../sam_pio_quickstart_use_case_2.html',1,'index']]],
  ['device_20',['device',['../twi_quickstart.html#twi_basic_use_case_usage_code_reading',1,'Example code : Reading from a slave device'],['../twi_quickstart.html#twi_basic_use_case_usage_code_writing',1,'Example code : Writing to a slave device']]],
  ['devicevectors_21',['DeviceVectors',['../sam4sd32c_8h.html#a064ea30c4aaba6c074d78c9575784b91',1,'sam4sd32c.h']]],
  ['digital_20converter_22',['Digital Converter',['../index.html#mainpage_adc',1,'ADC (Analog-to-Digital Converter)'],['../group___s_a_m4_s___a_d_c.html',1,'Analog-to-Digital Converter']]],
  ['digital_20converter_20adc_23',['Analog-to-digital Converter (ADC)',['../group__sam__drivers__adc__group.html',1,'']]],
  ['dis_5fsuc_5fnack_24',['dis_suc_nack',['../structusart__iso7816__opt__t.html#af5cea7c8c53aa409fd166e7d3c83ed85',1,'usart_iso7816_opt_t']]],
  ['disable_5fglobal_5finterrupt_25',['Disable_global_interrupt',['../group__interrupt__deprecated__group.html#ga4834270e1b8984fe025bce15e7ae1564',1,'interrupt_sam_nvic.h']]],
  ['document_20revision_20history_26',['Document Revision History',['../asfdoc_sam_drivers_tc_document_revision_history.html',1,'']]],
  ['documentation_27',['SAM4SD32 Driver Documentation',['../index.html',1,'']]],
  ['doing_20port_20access_28',['Advanced use case doing port access',['../ioport_quickstart_use_case_1.html',1,'ioport_quickstart']]],
  ['doxygen_5fcompat_2edox_29',['doxygen_compat.dox',['../doxygen__compat_8dox.html',1,'']]],
  ['driven_20edge_20detection_30',['Advanced use case - Interrupt driven edge detection',['../sam_pio_quickstart_use_case_2.html',1,'index']]],
  ['driver_31',['Driver',['../asfdoc_sam_drivers_tc_extra.html',1,'Extra Information for Timer Counter Driver'],['../group__asfdoc__sam__drivers__tc__group.html',1,'SAM3/4S/4L/4E/4N/4CM/4C/G Timer Counter (TC) Driver']]],
  ['driver_32',['driver',['../sam_pio_quickstart.html#sam_pio_quickstart_basic',1,'Basic usage of the PIO driver'],['../sam_pio_quickstart.html',1,'Quick Start Guide for the SAM PIO driver'],['../asfdoc_sam_drivers_tc_qsg.html',1,'Quick Start Guide for the TC driver'],['../sam_adc_quickstart.html',1,'Quickstart guide for SAM ADC driver'],['../sam_spi_quickstart.html',1,'Quickstart guide for SAM SPI driver']]],
  ['driver_20documentation_33',['SAM4SD32 Driver Documentation',['../index.html',1,'']]],
  ['driver_20sam_20drivers_20usart_34',['USART Low-Level Driver (sam/drivers/usart)',['../index.html#mainpage_serial_usart_low',1,'']]],
  ['drivers_20usart_35',['USART Low-Level Driver (sam/drivers/usart)',['../index.html#mainpage_serial_usart_low',1,'']]]
];
