var searchData=
[
  ['a_20character_0',['a character',['../sam_usart_quickstart.html#usart_basic_use_case',1,'Basic use case - transmit a character'],['../serial_quickstart.html#serial_basic_use_case',1,'Basic use case - transmit a character']]],
  ['a_20packet_20of_20serial_20data_1',['Advanced use case - Send a packet of serial data',['../serial_use_case_1.html',1,'serial_quickstart']]],
  ['a_20slave_20device_2',['a slave device',['../twi_quickstart.html#twi_basic_use_case_usage_code_reading',1,'Example code : Reading from a slave device'],['../twi_quickstart.html#twi_basic_use_case_usage_code_writing',1,'Example code : Writing to a slave device']]],
  ['access_3',['Advanced use case doing port access',['../ioport_quickstart_use_case_1.html',1,'ioport_quickstart']]],
  ['acronyms_4',['Acronyms',['../asfdoc_sam_drivers_tc_extra.html#asfdoc_sam_drivers_tc_extra_acronyms',1,'']]],
  ['adc_20analog_20to_20digital_20converter_5',['ADC (Analog-to-Digital Converter)',['../index.html#mainpage_adc',1,'']]],
  ['adc_20driver_6',['Quickstart guide for SAM ADC driver',['../sam_adc_quickstart.html',1,'index']]],
  ['advanced_20software_20framework_7',['What Is ASF (Advanced Software Framework)?',['../asf_overview.html',1,'index']]],
  ['advanced_20use_20case_201_8',['Advanced Use Case 1',['../sam_pio_quickstart_use_case_2.html#sam_pio_quickstart_use_case_2_overview',1,'']]],
  ['advanced_20use_20case_20doing_20port_20access_9',['Advanced use case doing port access',['../ioport_quickstart_use_case_1.html',1,'ioport_quickstart']]],
  ['advanced_20use_20case_20interrupt_20driven_20edge_20detection_10',['Advanced use case - Interrupt driven edge detection',['../sam_pio_quickstart_use_case_2.html',1,'index']]],
  ['advanced_20use_20case_20send_20a_20packet_20of_20serial_20data_11',['Advanced use case - Send a packet of serial data',['../serial_use_case_1.html',1,'serial_quickstart']]],
  ['advanced_20use_20cases_12',['Advanced use cases',['../adc_use_case_1.html',1,'Advanced use cases'],['../ioport_quickstart.html#ioport_quickstart_advanced',1,'Advanced use cases'],['../sam_pwm_quickstart.html#pwm_use_cases',1,'Advanced use cases'],['../sam_adc_quickstart.html#adc_use_cases',1,'Advanced use cases']]],
  ['analog_20to_20digital_20converter_13',['ADC (Analog-to-Digital Converter)',['../index.html#mainpage_adc',1,'']]],
  ['and_20echo_20back_14',['USART receive character and echo back',['../usart_use_case_1.html',1,'sam_usart_quickstart']]],
  ['and_20echo_20back_20via_20interrupts_15',['USART receive character and echo back via interrupts',['../usart_use_case_2.html',1,'sam_usart_quickstart']]],
  ['api_20overview_16',['API Overview',['../group__asfdoc__sam__drivers__tc__group.html#asfdoc_sam_drivers_tc_api_overview',1,'']]],
  ['apis_17',['APIs',['../index.html#mainpage_api',1,'']]],
  ['asf_20advanced_20software_20framework_18',['What Is ASF (Advanced Software Framework)?',['../asf_overview.html',1,'index']]],
  ['asf_20layer_20model_19',['ASF Layer Model',['../asf_overview.html#asf_overview_layers',1,'']]],
  ['asf_20provides_20',['What ASF Provides',['../asf_overview.html#asf_overview_contents',1,'']]],
  ['asynchronous_20receiver_20transmitter_21',['USART (Universal Synchronous/Asynchronous Receiver/Transmitter)',['../index.html#mainpage_serial_usart',1,'']]]
];
