var searchData=
[
  ['sam_20adc_20driver_0',['Quickstart guide for SAM ADC driver',['../sam_adc_quickstart.html',1,'index']]],
  ['sam_20drivers_20usart_1',['USART Low-Level Driver (sam/drivers/usart)',['../index.html#mainpage_serial_usart_low',1,'']]],
  ['sam_20pio_20driver_2',['Quick Start Guide for the SAM PIO driver',['../sam_pio_quickstart.html',1,'index']]],
  ['sam_20pwm_20module_3',['Quickstart guide for SAM PWM module',['../sam_pwm_quickstart.html',1,'index']]],
  ['sam_20spi_20driver_4',['Quickstart guide for SAM SPI driver',['../sam_spi_quickstart.html',1,'index']]],
  ['sam_20usart_20module_5',['Quick start guide for the SAM USART module',['../sam_usart_quickstart.html',1,'index']]],
  ['sam4sd32_20driver_20documentation_6',['SAM4SD32 Driver Documentation',['../index.html',1,'']]],
  ['scanf_7',['Basic use case - USART console with printf/scanf',['../stdio_serial_quickstart.html#stdio_serial_qs_use_case',1,'']]],
  ['send_20a_20packet_20of_20serial_20data_8',['Advanced use case - Send a packet of serial data',['../serial_use_case_1.html',1,'serial_quickstart']]],
  ['serial_9',['USART High-Level Serial Service (common/services/serial)',['../index.html#mainpage_serial_usart_high',1,'']]],
  ['serial_20data_10',['Advanced use case - Send a packet of serial data',['../serial_use_case_1.html',1,'serial_quickstart']]],
  ['serial_20interface_20service_11',['Quick start guide for Serial Interface service',['../serial_quickstart.html',1,'index']]],
  ['serial_20interfaces_12',['Serial Interfaces',['../index.html#mainpage_serial',1,'']]],
  ['serial_20peripheral_20interface_13',['SPI (Serial Peripheral Interface)',['../index.html#mainpage_serial_spi',1,'']]],
  ['serial_20service_20common_20services_20serial_14',['USART High-Level Serial Service (common/services/serial)',['../index.html#mainpage_serial_usart_high',1,'']]],
  ['serial_20use_20cases_15',['Serial use cases',['../serial_quickstart.html#serial_use_cases',1,'']]],
  ['service_16',['IOPORT (Input/Output Port Service)',['../index.html#mainpage_gpio_ioport',1,'']]],
  ['service_17',['service',['../serial_quickstart.html',1,'Quick start guide for Serial Interface service'],['../ioport_quickstart.html',1,'Quick start guide for the common IOPORT service']]],
  ['service_20common_20services_20serial_18',['USART High-Level Serial Service (common/services/serial)',['../index.html#mainpage_serial_usart_high',1,'']]],
  ['service_20twi_19',['Quickstart guide for Common service TWI',['../twi_quickstart.html',1,'index']]],
  ['services_20serial_20',['USART High-Level Serial Service (common/services/serial)',['../index.html#mainpage_serial_usart_high',1,'']]],
  ['setup_20code_21',['Setup Code',['../asfdoc_sam_drivers_tc_qsg.html#asfdoc_sam_drivers_tc_qsg_basic_capture_setup_code',1,'Setup Code'],['../asfdoc_sam_drivers_tc_qsg.html#asfdoc_sam_drivers_tc_qsg_basic_waveform_setup_code',1,'Setup Code']]],
  ['setup_20steps_22',['Setup Steps',['../asfdoc_sam_drivers_tc_qsg.html#asfdoc_sam_drivers_tc_qsg_basic_capture_setup',1,'Setup Steps'],['../asfdoc_sam_drivers_tc_qsg.html#asfdoc_sam_drivers_tc_qsg_basic_waveform_setup',1,'Setup Steps']]],
  ['setup_20steps_23',['Setup steps',['../stdio_serial_quickstart.html#stdio_serial_qs_setup',1,'Setup steps'],['../ioport_quickstart.html#ioport_quickstart_basic_setup',1,'Setup steps'],['../ioport_quickstart_use_case_1.html#ioport_quickstart_use_case_1_setup',1,'Setup steps'],['../sam_usart_quickstart.html#usart_basic_use_case_setup',1,'Setup steps'],['../usart_use_case_1.html#usart_use_case_1_setup',1,'Setup steps'],['../usart_use_case_2.html#usart_use_case_2_setup',1,'Setup steps'],['../serial_quickstart.html#serial_basic_use_case_setup',1,'Setup steps'],['../serial_use_case_1.html#serial_use_case_1_setup',1,'Setup steps'],['../sam_pwm_quickstart.html#pwm_basic_use_case_setup',1,'Setup steps'],['../pwm_use_case_1.html#pwm_use_case_1_setup',1,'Setup steps'],['../twi_quickstart.html#twi_basic_use_case_setup',1,'Setup steps'],['../sam_spi_quickstart.html#spi_basic_use_case_setup',1,'Setup steps'],['../sam_adc_quickstart.html#adc_basic_use_case_setup',1,'Setup steps'],['../adc_use_case_1.html#adc_use_case_1_setup',1,'Setup steps']]],
  ['slave_20device_24',['slave device',['../twi_quickstart.html#twi_basic_use_case_usage_code_reading',1,'Example code : Reading from a slave device'],['../twi_quickstart.html#twi_basic_use_case_usage_code_writing',1,'Example code : Writing to a slave device']]],
  ['software_20framework_25',['What Is ASF (Advanced Software Framework)?',['../asf_overview.html',1,'index']]],
  ['sources_26',['Documentation Sources',['../asf_overview.html#asf_overview_docs',1,'']]],
  ['special_20considerations_27',['Special Considerations',['../group__asfdoc__sam__drivers__tc__group.html#asfdoc_sam_drivers_tc_special_considerations',1,'']]],
  ['spi_20driver_28',['Quickstart guide for SAM SPI driver',['../sam_spi_quickstart.html',1,'index']]],
  ['spi_20serial_20peripheral_20interface_29',['SPI (Serial Peripheral Interface)',['../index.html#mainpage_serial_spi',1,'']]],
  ['start_20guide_20for_20serial_20interface_20service_30',['Quick start guide for Serial Interface service',['../serial_quickstart.html',1,'index']]],
  ['start_20guide_20for_20the_20common_20ioport_20service_31',['Quick start guide for the common IOPORT service',['../ioport_quickstart.html',1,'index']]],
  ['start_20guide_20for_20the_20sam_20pio_20driver_32',['Quick Start Guide for the SAM PIO driver',['../sam_pio_quickstart.html',1,'index']]],
  ['start_20guide_20for_20the_20sam_20usart_20module_33',['Quick start guide for the SAM USART module',['../sam_usart_quickstart.html',1,'index']]],
  ['start_20guide_20for_20the_20tc_20driver_34',['Quick Start Guide for the TC driver',['../asfdoc_sam_drivers_tc_qsg.html',1,'asfdoc_sam_drivers_tc_exqsg']]],
  ['start_20guide_20for_20usart_20stdio_20integration_35',['Quick Start Guide for USART STDIO Integration',['../stdio_serial_quickstart.html',1,'index']]],
  ['stdio_20does_36',['What STDIO Does',['../stdio_serial_quickstart.html#stdio_serial_qs_overview',1,'']]],
  ['stdio_20integration_37',['Quick Start Guide for USART STDIO Integration',['../stdio_serial_quickstart.html',1,'index']]],
  ['stdio_20integration_20common_20utils_20stdio_20stdio_5fserial_38',['USART STDIO Integration (common/utils/stdio/stdio_serial)',['../index.html#mainpage_serial_usart_stdio',1,'']]],
  ['stdio_20stdio_5fserial_39',['USART STDIO Integration (common/utils/stdio/stdio_serial)',['../index.html#mainpage_serial_usart_stdio',1,'']]],
  ['stdio_5fserial_40',['USART STDIO Integration (common/utils/stdio/stdio_serial)',['../index.html#mainpage_serial_usart_stdio',1,'']]],
  ['steps_41',['Steps',['../asfdoc_sam_drivers_tc_qsg.html#asfdoc_sam_drivers_tc_qsg_basic_capture_setup',1,'Setup Steps'],['../asfdoc_sam_drivers_tc_qsg.html#asfdoc_sam_drivers_tc_qsg_basic_waveform_setup',1,'Setup Steps']]],
  ['steps_42',['steps',['../stdio_serial_quickstart.html#stdio_serial_qs_setup',1,'Setup steps'],['../ioport_quickstart.html#ioport_quickstart_basic_setup',1,'Setup steps'],['../ioport_quickstart_use_case_1.html#ioport_quickstart_use_case_1_setup',1,'Setup steps'],['../sam_usart_quickstart.html#usart_basic_use_case_setup',1,'Setup steps'],['../usart_use_case_1.html#usart_use_case_1_setup',1,'Setup steps'],['../usart_use_case_2.html#usart_use_case_2_setup',1,'Setup steps'],['../serial_quickstart.html#serial_basic_use_case_setup',1,'Setup steps'],['../serial_use_case_1.html#serial_use_case_1_setup',1,'Setup steps'],['../sam_pwm_quickstart.html#pwm_basic_use_case_setup',1,'Setup steps'],['../pwm_use_case_1.html#pwm_use_case_1_setup',1,'Setup steps'],['../twi_quickstart.html#twi_basic_use_case_setup',1,'Setup steps'],['../sam_spi_quickstart.html#spi_basic_use_case_setup',1,'Setup steps'],['../sam_adc_quickstart.html#adc_basic_use_case_setup',1,'Setup steps'],['../adc_use_case_1.html#adc_use_case_1_setup',1,'Setup steps'],['../ioport_quickstart.html#ioport_quickstart_use_case_1_usage',1,'Usage steps'],['../ioport_quickstart_use_case_1.html#ioport_quickstart_use_case_2_usage',1,'Usage steps'],['../sam_usart_quickstart.html#usart_basic_use_case_usage',1,'Usage steps'],['../usart_use_case_1.html#usart_use_case_1_usage',1,'Usage steps'],['../usart_use_case_2.html#usart_use_case_2_usage',1,'Usage steps'],['../serial_quickstart.html#serial_basic_use_case_usage',1,'Usage steps'],['../serial_use_case_1.html#serial_use_case_1_usage',1,'Usage steps'],['../sam_pwm_quickstart.html#pwm_basic_use_case_usage',1,'Usage steps'],['../pwm_use_case_1.html#pwm_use_case_1_usage',1,'Usage steps'],['../twi_quickstart.html#twi_basic_use_case_usage',1,'Usage steps'],['../sam_adc_quickstart.html#adc_basic_use_case_usage',1,'Usage steps'],['../adc_use_case_1.html#adc_use_case_1_usage',1,'Usage steps']]],
  ['synchronous_20asynchronous_20receiver_20transmitter_43',['USART (Universal Synchronous/Asynchronous Receiver/Transmitter)',['../index.html#mainpage_serial_usart',1,'']]]
];
