var searchData=
[
  ['universal_20synchronous_20asynchronous_20receiver_20transmitter_0',['USART (Universal Synchronous/Asynchronous Receiver/Transmitter)',['../index.html#mainpage_serial_usart',1,'']]],
  ['usage_1',['Usage',['../asfdoc_sam_drivers_tc_qsg.html#asfdoc_sam_drivers_tc_qsg_basic_capture',1,'TC Capture Mode Basic Usage'],['../asfdoc_sam_drivers_tc_qsg.html#asfdoc_sam_drivers_tc_qsg_basic_waveform',1,'TC Waveform Mode Basic Usage'],['../asfdoc_sam_drivers_tc_example.html#asfdoc_sam_drivers_tc_example_usage',1,'Usage']]],
  ['usage_20of_20the_20pio_20driver_2',['Basic usage of the PIO driver',['../sam_pio_quickstart.html#sam_pio_quickstart_basic',1,'']]],
  ['usage_20steps_3',['Usage steps',['../ioport_quickstart.html#ioport_quickstart_use_case_1_usage',1,'Usage steps'],['../ioport_quickstart_use_case_1.html#ioport_quickstart_use_case_2_usage',1,'Usage steps'],['../sam_usart_quickstart.html#usart_basic_use_case_usage',1,'Usage steps'],['../usart_use_case_1.html#usart_use_case_1_usage',1,'Usage steps'],['../usart_use_case_2.html#usart_use_case_2_usage',1,'Usage steps'],['../serial_quickstart.html#serial_basic_use_case_usage',1,'Usage steps'],['../serial_use_case_1.html#serial_use_case_1_usage',1,'Usage steps'],['../sam_pwm_quickstart.html#pwm_basic_use_case_usage',1,'Usage steps'],['../pwm_use_case_1.html#pwm_use_case_1_usage',1,'Usage steps'],['../twi_quickstart.html#twi_basic_use_case_usage',1,'Usage steps'],['../sam_adc_quickstart.html#adc_basic_use_case_usage',1,'Usage steps'],['../adc_use_case_1.html#adc_use_case_1_usage',1,'Usage steps']]],
  ['usart_4',['USART Low-Level Driver (sam/drivers/usart)',['../index.html#mainpage_serial_usart_low',1,'']]],
  ['usart_20console_20with_20printf_20scanf_5',['Basic use case - USART console with printf/scanf',['../stdio_serial_quickstart.html#stdio_serial_qs_use_case',1,'']]],
  ['usart_20high_20level_20serial_20service_20common_20services_20serial_6',['USART High-Level Serial Service (common/services/serial)',['../index.html#mainpage_serial_usart_high',1,'']]],
  ['usart_20low_20level_20driver_20sam_20drivers_20usart_7',['USART Low-Level Driver (sam/drivers/usart)',['../index.html#mainpage_serial_usart_low',1,'']]],
  ['usart_20module_8',['Quick start guide for the SAM USART module',['../sam_usart_quickstart.html',1,'index']]],
  ['usart_20receive_20character_20and_20echo_20back_9',['USART receive character and echo back',['../usart_use_case_1.html',1,'sam_usart_quickstart']]],
  ['usart_20receive_20character_20and_20echo_20back_20via_20interrupts_10',['USART receive character and echo back via interrupts',['../usart_use_case_2.html',1,'sam_usart_quickstart']]],
  ['usart_20stdio_20integration_11',['Quick Start Guide for USART STDIO Integration',['../stdio_serial_quickstart.html',1,'index']]],
  ['usart_20stdio_20integration_20common_20utils_20stdio_20stdio_5fserial_12',['USART STDIO Integration (common/utils/stdio/stdio_serial)',['../index.html#mainpage_serial_usart_stdio',1,'']]],
  ['usart_20universal_20synchronous_20asynchronous_20receiver_20transmitter_13',['USART (Universal Synchronous/Asynchronous Receiver/Transmitter)',['../index.html#mainpage_serial_usart',1,'']]],
  ['usart_20use_20cases_14',['USART use cases',['../sam_usart_quickstart.html#usart_use_cases',1,'']]],
  ['use_20case_15',['use case',['../ioport_quickstart.html#ioport_quickstart_basic',1,'Basic use case'],['../sam_pwm_quickstart.html#pwm_basic_use_case',1,'Basic use case'],['../twi_quickstart.html#twi_basic_use_case',1,'Basic use case'],['../sam_spi_quickstart.html#spi_basic_use_case',1,'Basic use case'],['../sam_adc_quickstart.html#adc_basic_use_case',1,'Basic use case']]],
  ['use_20case_201_16',['Advanced Use Case 1',['../sam_pio_quickstart_use_case_2.html#sam_pio_quickstart_use_case_2_overview',1,'']]],
  ['use_20case_201_17',['Use case #1',['../pwm_use_case_1.html',1,'sam_pwm_quickstart']]],
  ['use_20case_20doing_20port_20access_18',['Advanced use case doing port access',['../ioport_quickstart_use_case_1.html',1,'ioport_quickstart']]],
  ['use_20case_20interrupt_20driven_20edge_20detection_19',['Advanced use case - Interrupt driven edge detection',['../sam_pio_quickstart_use_case_2.html',1,'index']]],
  ['use_20case_20send_20a_20packet_20of_20serial_20data_20',['Advanced use case - Send a packet of serial data',['../serial_use_case_1.html',1,'serial_quickstart']]],
  ['use_20case_20transmit_20a_20character_21',['use case transmit a character',['../sam_usart_quickstart.html#usart_basic_use_case',1,'Basic use case - transmit a character'],['../serial_quickstart.html#serial_basic_use_case',1,'Basic use case - transmit a character']]],
  ['use_20case_20usart_20console_20with_20printf_20scanf_22',['Basic use case - USART console with printf/scanf',['../stdio_serial_quickstart.html#stdio_serial_qs_use_case',1,'']]],
  ['use_20cases_23',['Use Cases',['../asfdoc_sam_drivers_tc_qsg.html#asfdoc_sam_drivers_tc_qsg_use_cases',1,'']]],
  ['use_20cases_24',['use cases',['../adc_use_case_1.html',1,'Advanced use cases'],['../ioport_quickstart.html#ioport_quickstart_advanced',1,'Advanced use cases'],['../sam_pwm_quickstart.html#pwm_use_cases',1,'Advanced use cases'],['../sam_adc_quickstart.html#adc_use_cases',1,'Advanced use cases'],['../sam_pio_quickstart.html#sam_pio_usecases',1,'PIO use cases'],['../serial_quickstart.html#serial_use_cases',1,'Serial use cases'],['../sam_usart_quickstart.html#usart_use_cases',1,'USART use cases']]],
  ['utils_20stdio_20stdio_5fserial_25',['USART STDIO Integration (common/utils/stdio/stdio_serial)',['../index.html#mainpage_serial_usart_stdio',1,'']]]
];
