var topics =
[
    [ "Power Management Controller (PMC)", "group__sam__drivers__pmc__group.html", "group__sam__drivers__pmc__group" ],
    [ "System Clock Management (sysclock)", "group__sysclk__group.html", "group__sysclk__group" ],
    [ "Peripheral Parallel Input/Output (PIO) Controller", "group__sam__drivers__pio__group.html", "group__sam__drivers__pio__group" ],
    [ "Busy-Wait Delay Routines", "group__group__common__services__delay.html", "group__group__common__services__delay" ],
    [ "General Purpose Input/Output", "group__gpio__group.html", "group__gpio__group" ],
    [ "Common IOPORT API", "group__ioport__group.html", "group__ioport__group" ],
    [ "SAM3/4S/4L/4E/4N/4CM/4C/G Timer Counter (TC) Driver", "group__asfdoc__sam__drivers__tc__group.html", "group__asfdoc__sam__drivers__tc__group" ],
    [ "Global interrupt management", "group__interrupt__group.html", "group__interrupt__group" ],
    [ "Universal Synchronous Asynchronous Receiver", "group__group__sam__drivers__usart.html", "group__group__sam__drivers__usart" ],
    [ "Universal Synchronous Asynchronous", "group__sam__drivers__usart__group.html", "group__sam__drivers__usart__group" ],
    [ "Serial Interface (Serial)", "group__serial__group.html", null ],
    [ "Pulse Width Modulation (PWM)", "group__sam__drivers__pwm__group.html", "group__sam__drivers__pwm__group" ],
    [ "Two-Wire Interface (TWI)", "group__sam__drivers__twi__group.html", "group__sam__drivers__twi__group" ],
    [ "Two Wire-interface(TWI)", "group__twi__group.html", "group__twi__group" ],
    [ "Serial Peripheral Interface (SPI)", "group__sam__drivers__spi__group.html", "group__sam__drivers__spi__group" ],
    [ "Analog-to-digital Converter (ADC)", "group__sam__drivers__adc__group.html", "group__sam__drivers__adc__group" ],
    [ "Timer Counter", "group___s_a_m4_s___t_c.html", null ],
    [ "SAM4SD32C definitions", "group___s_a_m4_s_d32_c__definitions.html", null ],
    [ "CMSIS Definitions", "group___s_a_m4_s_d32_c__cmsis.html", null ],
    [ "Peripheral Software API", "group___s_a_m4_s_d32_c__api.html", null ],
    [ "Registers Access Definitions", "group___s_a_m4_s_d32_c__reg.html", null ],
    [ "Peripheral Ids Definitions", "group___s_a_m4_s_d32_c__id.html", null ],
    [ "Peripheral Base Address Definitions", "group___s_a_m4_s_d32_c__base.html", null ],
    [ "Peripheral Pio Definitions", "group___s_a_m4_s_d32_c__pio.html", null ],
    [ "Parallel Input/Output Controller", "group___s_a_m4_s___p_i_o.html", null ],
    [ "Universal Synchronous Asynchronous Receiver Transmitter", "group___s_a_m4_s___u_s_a_r_t.html", null ],
    [ "Pulse Width Modulation Controller", "group___s_a_m4_s___p_w_m.html", null ],
    [ "Two-wire Interface", "group___s_a_m4_s___t_w_i.html", null ],
    [ "Serial Peripheral Interface", "group___s_a_m4_s___s_p_i.html", null ],
    [ "Analog-to-Digital Converter", "group___s_a_m4_s___a_d_c.html", null ]
];